name: merging-test
on:
  pull_request:
    branches:
      - main
jobs:
    test:
        runs-on: ubuntu-latest

        steps:
          - name: checkout branch code
            uses: actions/checkout@v3

          - name: configuring python
            run:
                pip install -r requirements.txt

          - name: run test
            run:
              pytest --maxfail=1 --disable-warnings

